"""Adding 'is_profile' attribute into Image table

Revision ID: 1de884f56c1c
Revises: 8119e2ea5441
Create Date: 2025-08-09 20:34:14.391527

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "1de884f56c1c"
down_revision: Union[str, None] = "8119e2ea5441"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("images", sa.Column("is_profile", sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("images", "is_profile")
    # ### end Alembic commands ###
