"""Updating type of value in Expenses table

Revision ID: 3ac1a8f1bdd0
Revises: 91473017f97e
Create Date: 2025-10-16 21:08:31.532571

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "3ac1a8f1bdd0"
down_revision: Union[str, None] = "91473017f97e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "expenses",
        "value",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        type_=sa.Numeric(),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "expenses",
        "value",
        existing_type=sa.Numeric(),
        type_=sa.DOUBLE_PRECISION(precision=53),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
