"""Adding monthly_revenue column

Revision ID: 91473017f97e
Revises: c163632ec29c
Create Date: 2025-10-16 20:56:12.785779

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "91473017f97e"
down_revision: Union[str, None] = "c163632ec29c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("monthly_revenue", sa.Numeric(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "monthly_revenue")
    # ### end Alembic commands ###
