"""Creating label table and applying relation with expense and user tables

Revision ID: 963df197cbd4
Revises: 1de884f56c1c
Create Date: 2025-08-22 09:18:30.155770

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "963df197cbd4"
down_revision: Union[str, None] = "1de884f56c1c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "labels",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("color", sa.String(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_labels_id"), "labels", ["id"], unique=False)
    op.add_column("expenses", sa.Column("label_id", sa.Integer(), nullable=True))
    op.create_foreign_key(None, "expenses", "labels", ["label_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "expenses", type_="foreignkey")
    op.drop_column("expenses", "label_id")
    op.drop_index(op.f("ix_labels_id"), table_name="labels")
    op.drop_table("labels")
    # ### end Alembic commands ###
