"""create monthly_snapshots table

Revision ID: a0d8262613f4
Revises: abf9ad7d967c
Create Date: 2025-12-27 22:09:20.337761

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "a0d8262613f4"
down_revision: Union[str, None] = "abf9ad7d967c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "monthly_snapshots",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("current_revenue", sa.Numeric(), nullable=False),
        sa.Column("year_month", sa.String(), nullable=False),
        sa.Column("total_spent", sa.Numeric(), nullable=False),
        sa.Column("total_by_label", sa.JSON(), nullable=False),
        sa.Column("percentage_by_label", sa.JSON(), nullable=False),
        sa.Column("total_by_payment_type", sa.JSON(), nullable=False),
        sa.Column("total_by_card", sa.JSON(), nullable=False),
        sa.Column("started_at", sa.Date(), nullable=False),
        sa.Column("ended_at", sa.Date(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_monthly_snapshots_id"), "monthly_snapshots", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_monthly_snapshots_year_month"),
        "monthly_snapshots",
        ["year_month"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_monthly_snapshots_year_month"), table_name="monthly_snapshots"
    )
    op.drop_index(op.f("ix_monthly_snapshots_id"), table_name="monthly_snapshots")
    op.drop_table("monthly_snapshots")
    # ### end Alembic commands ###
